export const SAVINGS_GOAL_CALCULATOR_ACTION_TYPES = {
  SET_SAVINGS_GOAL_RESULT: "savings-goal-calculator/SET_SAVINGS_GOAL_RESULT",
  SET_SAVINGS_GOAL_SCHEDULE_RESULT: "savings-goal-calculator/SET_SAVINGS_GOAL_SCHEDULE_RESULT"
}